name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]

    services:
      mariadb:
        image: mariadb:lts
        env:
            MARIADB_ROOT_PASSWORD: ${{secrets.MARIADB_ROOT_PASSWORD}}
            MARIADB_DATABASE: ${{secrets.MARIADB_DATABASE}}
            MARIADB_USER: ${{secrets.MARIADB_USER}}
            MARIADB_PASSWORD: ${{secrets.MARIADB_PASSWORD}}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -h 127.0.0.1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
        cache: maven

    - name: Run tests
      run: mvn test

    - name: Build with Maven
      run: mvn -B package -DskipTests

    - name: Login to Dockerhub
      if: github.event_name == 'push'
      run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

    - name: build image
      if: github.event_name == 'push'
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/review-service:${{github.sha}} -t ${{secrets.DOCKERHUB_USERNAME}}/review-service:staging .

    - name: push to docker hub
      if: github.event_name == 'push'
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/review-service:${{github.sha}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/review-service:staging

    env:
        DB_URL: jdbc:mariadb://localhost:3306/${{secrets.MARIADB_DATABASE}}
        DB_USERNAME: ${{secrets.MARIADB_USER}}
        DB_PASSWORD: ${{secrets.MARIADB_PASSWORD}}
